Feature/ted 87 metadata normaliser - extractor
meaningfy-ws/ted-sws pull request #14
Opened 2022-02-24 17:17 UTC by Dragos0000

2022-02-24 18:02 UTC, costezki requested changes
I like your efforts in figuring out XPaths! Also good start in organising the domain and service layers. We need some refactoring and simplification.

2022-02-24 18:02 UTC, costezki commented on tests/unit/notice_normaliser/test_metadata_extractor.py
> +    assert notice_2018.ted_id in extracted_metadata_dict["notice_publication_number"]
why only this key? 

You see, This is the reason why I recommended to list the keys as variables in the "feature file"

2022-02-24 18:02 UTC, costezki commented on tests/unit/notice_normaliser/test_metadata_normaliser.py
> +def test_metadata_extractor(raw_notice):
this might be a bit more sophisticated

2022-02-27 09:25 UTC, Dragos0000 commented on ted_sws/metadata_normaliser/services/__init__.py
> +def xpath_extract_attributes(elements: List[Element], attrib_key: str) -> List[str]:
renamed

2022-02-27 09:31 UTC, Dragos0000 commented on ted_sws/metadata_normaliser/services/__init__.py
> +class ExtractMetadata:
moved and renamed

2022-02-27 09:41 UTC, Dragos0000 commented on tests/conftest.py
> +    return TedAPIAdapter(request_api=FakeRequestAPI())
for  testing with fakes

2022-02-27 09:43 UTC, Dragos0000 commented on tests/conftest.py
> +import base64
we need to decode the content ... as a notice for us is a api response

2022-03-03 08:40 UTC, costezki approved these changes
It is good to go after all the previous comments are addressed.

2022-03-03 08:40 UTC, costezki commented on ted_sws/metadata_normaliser/services/xml_manifestation_metadata_extractor.py
> +        return EncodedValue(code=extract_attribute_from_element(element=element, attrib_key="CODE"),
Warning: we might not always have "CODE" attribute; it is worth having it as a default variable.

2022-03-11 14:30 UTC, merged